job('First-Maven-Project-Via-DSL') {
  description("First Maven job generated by the DSL on ${new Date()}")
  scm {
    git("https://github.com/never-potm/Jenkins-tutorial.git", master)
  }
  triggers {
    scm('* * * * *')
  }
  steps {
    maven('clean package', 'pom.xml')
  }
  publishers {
    archiveArtifacts '**/*.jar'
  }
}
